# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, unique=True, verbose_name='主机名')),
                ('cpu_model', models.CharField(blank=True, max_length=128, verbose_name='CPU型号')),
                ('cpu_count', models.CharField(max_length=10, null=True, verbose_name='物理cpu个数')),
                ('cpu_core_count', models.CharField(max_length=10, null=True, verbose_name='cpu核数')),
                ('memory', models.CharField(blank=True, max_length=32, null=True, verbose_name='内存大小')),
                ('sn', models.CharField(blank=True, max_length=128, verbose_name='SN号 码')),
                ('asset_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='设备类型')),
                ('status', models.IntegerField(blank=True, choices=[(0, '使用中'), (1, '未使用'), (2, '故障'), (3, '其它')], default=0, null=True, verbose_name='设备状态')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='操作系统')),
                ('ip', models.CharField(max_length=255, unique=True, verbose_name='IP')),
                ('disk', models.CharField(blank=True, max_length=255, null=True, verbose_name='硬盘信息')),
                ('vendor', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备厂商')),
                ('memo', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='组名')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='描述')),
            ],
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='机房名称')),
                ('address', models.CharField(max_length=128, null=True, verbose_name='机房地址')),
                ('tel', models.CharField(max_length=30, null=True, verbose_name='机房电话')),
                ('contact', models.CharField(max_length=30, null=True, verbose_name='客户经理')),
                ('contact_phone', models.CharField(max_length=30, null=True, verbose_name='移动电话')),
                ('cabinet', models.CharField(max_length=32, null=True, verbose_name='机柜信息')),
                ('ip_range', models.CharField(max_length=30, null=True, verbose_name='IP范围')),
                ('bandwidth', models.CharField(max_length=30, null=True, verbose_name='接入带宽')),
            ],
            options={
                'verbose_name': '数据中心',
                'verbose_name_plural': '数据中心',
            },
        ),
        migrations.CreateModel(
            name='IpSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net', models.CharField(max_length=30)),
                ('subnet', models.CharField(max_length=30, null=True)),
                ('describe', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('ip', models.GenericIPAddressField(null=True, verbose_name='IP地址')),
                ('desc', models.CharField(max_length=128, null=True, verbose_name='描述')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.HostGroup', verbose_name='设备组')),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.HostGroup', verbose_name='设备组'),
        ),
        migrations.AddField(
            model_name='host',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Idc', verbose_name='所在机房'),
        ),
    ]
